import '@/public/style/globals.scss';
import styles from './layout.module.scss';
import type { Metadata } from 'next';
import { Footer, Header, Sidebar } from './components';

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
 return (
  <html lang='ru'>
   <head></head>
   <body>
    <div className={styles.wrapper}>
     <Header className={styles.header} />
     <Sidebar className={styles.sidebar} />
     <div className={styles.body}>{children}</div>
     <Footer className={styles.footer} />
    </div>
   </body>
  </html>
 );
}
